version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: agt
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend/app:/code/app
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/code/src
    env_file:
      - ./env/frontend.env
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
